### ISSUE TITLE
Fontawesome 4.7 ?

### ISSUE THREAD

**Issue by C3cile** [Codeinwp/wp-menu-icons#116]
Hello,
Your plugin is one of my favourite. l install it on all Wp site I make. 
But, for my last project, I need icons from Fontawesome 4.7 ... and your plugin implement the 4.6.1 version...
Do you think you are going to implement the 4.7 version soon ?

Thanks for reading me,

C3cile

**Comment by HardeepAsrani** [comment]
Closes due to https://github.com/Codeinwp/wp-menu-icons/issues/130
