### ISSUE TITLE
update authors + plugin

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/wp-menu-icons#119]
@selul few things that I have in mind: 

0. Update font-awesome to latest version

1. add the dashboard widget

2. Redo banner + icon, make sure parrot is in the banner 📃 

3. redo the right  area on the select icon screen : https://www.dropbox.com/s/2g8rgx3zrzttyxi/Screenshot%202017-12-22%2021.30.52.png?dl=0

a) Keep existing text, but instead recommend the advanced css plugin
b) Add an email course widget : https://www.dropbox.com/s/oxaieckaaqigopx/Screenshot%202017-12-22%2021.32.26.png?dl=0
c) Add a banner/recommendation for Hestia, like : https://www.dropbox.com/s/0y4vt7jqkfrnn6i/Screenshot%202017-12-22%2021.33.23.png?dl=0

**Comment by ineagu** [comment]
I have also updated the description on develop branch, let me know when we can push an update

**Comment by selul** [comment]
@ineagu most of them are solved and released, it's missing the email course and hestia upsell. i will ask rohit for help here.
