### ISSUE TITLE
improve sidebar area

### ISSUE THREAD

**Issue by selul** [Codeinwp/wp-menu-icons#122]
@rohittm i would need your help in adding 2 new areas here: 
 -> https://www.dropbox.com/s/2g8rgx3zrzttyxi/Screenshot%202017-12-22%2021.30.52.png?dl=0
 
a) Add an email course widget : https://www.dropbox.com/s/oxaieckaaqigopx/Screenshot%202017-12-22%2021.32.26.png?dl=0 -> Check the one from Login Customizer
b) Add a banner/recommendation for Hestia, like : https://www.dropbox.com/s/0y4vt7jqkfrnn6i/Screenshot%202017-12-22%2021.33.23.png?dl=0 -> Check the one from Pirate Forms. 

Let me know if you have any questions.

**Comment by rohittm** [comment]
@selul PR #123

**Comment by selul** [comment]
@rohittm have you tested this? When I click on subscribe I get an error.

**Comment by rohittm** [comment]
@selul I re-used this code from pirate forms thinking that it is some API call. later I found out that the file was missing ( Which I reported here: https://github.com/Codeinwp/pirate-forms/issues/262 ) and after including the file, there is some API error (which is also reported in the same issue). Working on that.

**Comment by rohittm** [comment]
@selul fixed it as well. Check PR #123

**Comment by selul** [comment]
@rohittm after I click submit, the page is refreshed, it should be an ajax request. 
Also, the box still shows after I click submit, it should be hidden after.
The orange box for Hestia upsell is not cool, it should copy the design of the subscribe box, and the button should be the same as WordPress core one. I know that in pirate forms is using this design, but for this plugin, i don't think it makes too much sense.

**Comment by rohittm** [comment]
Sure @selul, making the changes.

**Comment by selul** [comment]
@rohittm you forgot to add a check if the user subscribed, to no longer show that box. I've done it myself.
