### ISSUE TITLE
Settings don't work

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/wp-menu-icons#142]
Wanted to add some stuff to the plugin but can't update its settings in Appearance > Menus, the small sidebar area on the left. If I change and save, the AJAX request fails to save the settings, and I don't see any changes.

Can anyone test?

**Comment by johnh10** [comment]
I just encountered this myself across several sites while installing the plugin.

Clicking the 'Save Settings' in the 'Menu Icon Settings' sidebar on the nav-menus.php page just ends up with a spinning circle that never does save changes. Waited an hour... still spinning. No errors.

I'm surprised this ticket is over a year old without a response.

**Comment by HardeepAsrani** [comment]
The development of this plugin had stopped. I'm taking care of the tickets now. @johnh10 

I will fix it soon!

**Comment by HardeepAsrani** [comment]
Fixed. @johnh10
