### ISSUE TITLE
Looks like Menu Icons was installed via Composer. Please activate Icon Picker first.

### ISSUE THREAD

**Issue by sorshawitch** [Codeinwp/wp-menu-icons#148]
I have this message in the backend and I can't see the icons

**Comment by SupahDuck** [comment]
I have this error message persisting in the WP Dashboard as well.  Fresh install of WP5 on PHP 7.1.

Version 0.11.3 of "Menu Icons", but no "Icon Picker" functionality to be found anywhere.

**Comment by franceswest** [comment]
Fixed! 0.11.4 available. Didn't show immediately but when to the details link in plugin.

**Comment by SupahDuck** [comment]
Updated to 0.11.4, and now functioning properly.  Thanks for the quick response!  :-)

**Comment by selul** [comment]
Indeed, we have rolled out a fix into 0.11.4 version, thanks a lot for understanding.
