### ISSUE TITLE
Hover issue

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/wp-menu-icons#151]
@contactashish13 we have an issue with the hover a menu item when the Menu Icon and our Hestia theme are both installed and active. If you hover the submenu and keep the mouse on it for dew second, the title will appear here with the HTML text. Please see the image attached: 

<img width="1411" alt="screenshot 2019-02-19 at 2 27 56 pm" src="https://user-images.githubusercontent.com/6906834/53002923-dd39e680-3453-11e9-9b87-a7052a8fce06.png">

To replicate this, just install the Hestia theme and Menu Icons plugin and after creating a submenu just hover it for three seconds. 

Here is happening on the customer webiste as well: 

https://themeisle.com/index.php?gf-download=2019%2F02%2FCapture-d%E2%80%99e%CC%81cran-2019-02-11-a%CC%80-23.15.46.jpg&form-id=1&field-id=19&hash=3530d171c73d042a422a9d472faa51a793146e86c28c9a2782b2da33c028d0c0

I have attached as well a short video that might help: https://www.dropbox.com/s/8pualq8r0sxy6re/Screen%20Recording%202019-02-19%20at%202.36.58%20PM.mov?dl=0

Let me know if there is anything else I can help with.

Customer ticket: https://secure.helpscout.net/conversation/777126262/181112?folderId=212388

**Comment by contactashish13** [comment]
@mileamadalin I can't seem to reproduce this exactly. This is what I get:

![image](https://user-images.githubusercontent.com/12953439/53315346-a860e000-38e8-11e9-88b9-be421cb3c43a.png)

**Comment by mileamadalin** [comment]
@contactashish13 Tested again, and the issue persists: 

![screenshot 2019-02-25 at 08 57 32](https://user-images.githubusercontent.com/6906834/53319541-785f1000-38db-11e9-8bb7-357b515b360a.png)

WordPress: 5.1
Hestia: 2.2.1
Menu Icon:  0.11.4 

I saw in the image that you have attached you use WordPress 4.9.6. Could you please try with the latest version of WordPress? And as well form Hestia and Menu Icon.

**Comment by contactashish13** [comment]
@mileamadalin I don't see any difference with that configuration. Can you share a poopy instance where this can be reproduced?

**Comment by mileamadalin** [comment]
@contactashish13 I will close this one. The issue was opened here as well: https://github.com/Codeinwp/hestia-pro/issues/2043 and fixed. 

The problem occurs only when OrbitFox and Menu Icons plugins were both activated.
