### ISSUE TITLE
PHP warning

### ISSUE THREAD

**Issue by PlanetThoughts** [Codeinwp/wp-menu-icons#153]
These two lines frequently come up when first starting up WP admin:

PHP Warning: array_merge(): Argument #1 is not an array in C:\home\insightandenergy.com\wwwroot\wp\wp-content\plugins\menu-icons\vendor\codeinwp\themeisle-sdk\class-themeisle-sdk-widget-dashboard-blog.php on line 375
PHP Warning: Invalid argument supplied for foreach() in C:\home\insightandenergy.com\wwwroot\wp\wp-content\plugins\menu-icons\vendor\codeinwp\themeisle-sdk\class-themeisle-sdk-widget-dashboard-blog.php on line 376

Then, when refreshing the page, it loads fine from then on and allows normal access to the site's admin area. It is a nuisance, but I want to make sure it does not get any worse. 

I am running WP 5.1.1 and PHP 7.2.1, with Story theme.

Suggestions? TIA.

**Comment by poonam279** [comment]
The same issue reported here: https://wordpress.org/support/topic/array_merge-argument-1-is-not-an-array-2/

**Comment by grappler** [comment]
It seems like just the `codeinwp/themeisle-sdk` needs to be updated and new version released. Would be good to plan it with the release of WP 5.2.

**Comment by grappler** [comment]
@selul Do you think you could have a look?

**Comment by selul** [comment]
@grappler yes, you are right. I will roll out a fix. 

Thanks for letting me know.
