### ISSUE TITLE
Many icons missing

### ISSUE THREAD

**Issue by nahasco** [Codeinwp/wp-menu-icons#158]
Many icons from fontawesome are missing

**Comment by radu-themeisle** [comment]
@nahasco can you point out some of the missing icons? They should all be there.

**Comment by nahasco** [comment]
Xbox, Playstation, Microsoft, Nintendo.

**Comment by radu-themeisle** [comment]
The plugin uses the icons provided by Fontawesome v4.7 so there will be icons from v5 which will not be present.
You can download the icons you need and upload them to your website: http://prntscr.com/o7bu8t[](url)

**Comment by nahasco** [comment]
Why dont you guys update the plugin?! Fontawesome's current version is 5.9 and you're on 4.7?!

**Comment by radu-themeisle** [comment]
We tried when v5 came out but unfortunately the risk of conflicts is very high and users would have to manually change some icons which have a different UTF-8 code in v5.x than in v4.7.
At the moment themes and plugins using v4.7 are still widespread and icons not showing up when using v5 is a huge risk that would not benefit users. Even Fontawesome doesn't recommend using v4.7 and 5.x alongside and also don't provide a "clean way" to transition other than modifying the code which would definitely cause issues on the front end.
For the moment the safest option is to download a v5.x icon and upload it via the plugin.

**Comment by nahasco** [comment]
Oh, I understand. Porto theme is using the latest version though.

**Comment by radu-themeisle** [comment]
Thank you for the tip, we'll look into what they've done and how they managed to handle potential conflicts 😃

**Comment by richrd** [comment]
What about providing the two major versions of FontAwesome and letting the user select between FontAwesome 4 and FontAwesome 5?
