### ISSUE TITLE
Unable to select icon after upgrading WP to 5.3

### ISSUE THREAD

**Issue by chetansatasiya** [Codeinwp/wp-menu-icons#160]
https://wordpress.org/support/topic/unable-to-select-icon-after-upgrading-wp-to-5-3/

**Comment by selul** [comment]
Hi, the latest version of v0.12 should fix the issue.

**Comment by chetansatasiya** [comment]
Hey there,

We have updated the latest release but if you navigate different tab it will showing blank white page.
