### ISSUE TITLE
[WP 5.4] Duplicated Select icon

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/wp-menu-icons#162]
In WP 5.4 there are two Select icons, and just one of them actually work.
![Screenshot (4)](https://user-images.githubusercontent.com/3266155/78664491-cc109b00-78dc-11ea-9249-31f4a6c356cb.png)

Also reported here https://wordpress.org/support/topic/error-with-2-select-icon-in-admin/

**Comment by HardeepAsrani** [comment]
Fixed via https://github.com/HardeepAsrani/wp-menu-icons/commit/38a3b3455598510da96175ab7fe27510ae14fbe6
