### ISSUE TITLE
No need for custom menu item Walker in WP 5.4

### ISSUE THREAD

**Issue by AndreiIgna** [Codeinwp/wp-menu-icons#163]
From WordPress 5.4 onwards there's no need for a custom walker for menu items.
https://make.wordpress.org/core/2020/02/25/wordpress-5-4-introduces-new-hooks-to-add-custom-fields-to-menu-items/

There should be a check for WP version, and include it only for older versions in:
https://github.com/Codeinwp/wp-menu-icons/blob/f53c2ed3da76b7719950566643242d8f0ee1ca84/includes/picker.php#L51

This code may break other plugins using WP 5.4 and can be fixed easily with this check

**Comment by AndreiIgna** [comment]
In a lot of cases, on WordPress 5.4, this code causes duplicate icons or fields.

`wp_nav_menu_item_custom_fields` hook is added in WP core now, and `menu-item-custom-fields` adds it again. Any plugin / theme that extends the hook gets executed twice.

**Comment by HardeepAsrani** [comment]
Thanks, @AndreiIgna! Added it via https://github.com/HardeepAsrani/wp-menu-icons/commit/38a3b3455598510da96175ab7fe27510ae14fbe6
