### ISSUE TITLE
Update backlink on wp.org

### ISSUE THREAD

**Issue by adelina17** [Codeinwp/wp-menu-icons#175]
One more backlink update, this time on this page: https://wordpress.org/plugins/menu-icons/

It's this link: http://prntscr.com/tlay51

From https://codeinwp.com/blog/ to https://www.codeinwp.com/blog/

@contactashish13 

Thanks!

**Comment by contactashish13** [comment]
@selul are we still maintaining this plugin? I'm not sure who the primary for this is since I haven't done anything on this in years. I see the last commits on this were by you and Hardeep.

**Comment by selul** [comment]
Yes, we still maintain it, @HardeepAsrani started to show some love to it recently and he could help with the links too.

**Comment by adelina17** [comment]
Seems to be solved, thanks!
