### ISSUE TITLE
Libraries are not visible

### ISSUE THREAD

**Issue by Psytanium** [Codeinwp/wp-menu-icons#184]
Hi,

I only have Dashicons available, the left side menu where I can choose a library is not visible.

Thanks

**Comment by girishkrishaweb** [comment]
@Psytanium I checked the above issue with the latest version of WP & Plugin but I couldn't able to reproduce it. Is it possible you can share steps Or screenshots/videos?

**Comment by Psytanium** [comment]
Hi, I deactivated all plugins and tried but still don't have the library on the left side as per the plugin screenshots. I attached screenshots from my website. 

- https://ibb.co/sFd2vQm
- https://ibb.co/7QFrTCk

Thank you

**Comment by girishkrishaweb** [comment]
@Psytanium Thank you for sharing detail with us.

Can you please confirm with us that you have selected libraries from **Menu icon settings** of the left side bottom menus list? https://imgbb.com/sFd2vQm

Thanks.

**Comment by Psytanium** [comment]
I didn't seee it before, thank you very much.. found it and its working. perfect plugin

**Comment by selul** [comment]
Happy to hear that @Psytanium
