### ISSUE TITLE
Is this plugin abandoned? 

### ISSUE THREAD

**Issue by HenrijsS** [Codeinwp/wp-menu-icons#195]
I put up a review [here](https://wordpress.org/support/topic/very-good-plugin-but-small-icon-amount/) and Lucia said that this plugin is now retired.

What was the reasoning behind this? It's an awesome plugin!
Is there maybe a small documentation on updating and adding new FontAwesome icons?

I see the `vendor/codeinwp/icon-picker/includes/types/fa.php` file and it has all icons pre-written there. 
Was this auto-generated or typed out by hand?

I could provide an update for the newest versions of FontAwesome if possible.

**Comment by cristian-ungureanu** [comment]
@HenrijsS that was an error from our end, I am sorry for it. The plugin is not abandoned but it's not a priority for us so a new release would happen once in 3 / 4 months.
I will close this issue and open a new one about outdated icons. The `fa.php `file is part of a composer dependency from https://github.com/Codeinwp/icon-picker, I don't think it's generated.
As it's an open-source project, you are welcome to contribute if you want to.

Thank you and have a great day!

**Comment by HenrijsS** [comment]
@cristian-ungureanu Thank you for the response!

I somehow got it updated, but I couldn't understand from the code, which part uses which FA version.
I replaced the `fontawesome.min.css` file in the icon-picker/includes folder and generated a small NodeJS script that fetches the class-names of all icons and then creates a txt file with the array that can later be copied into the `types/fa.php` file.
I know it's not the best solution, so maybe there's a more general approach to updating the FontAwesome version?

My theme already uses the latest version of FontAwesome and now it's just a mess.
Icon picker and wp-menu-icons uses separate font versions and my theme has the third.

The addition by CDN also didn't work as it didn't add the newest icons and messed up all the backend.

Here's the simple NodeJS script that I wrote to fetch all the classes and get the array:
```js
const fs = require('fs');

const regex = /(fa-[a-z0-9\-]+)/g;
// Read all font-awesome classes from font-awesome.min.css and create variable from them
const faClasses = fs.readFileSync('font-awesome.min.css', 'utf8').match(regex);
const faClassesString = faClasses
	.map((faClass) => {
		const name = faClass.replace('fa-', '').replace(/-/g, ' ');
		const nameCapitalized = name.charAt(0).toUpperCase() + name.slice(1);
		return `array('group' => 'a11y', 'id' => '${faClass}', 'name' => __('${nameCapitalized}', 'icon-picker')),`;
	})
	.join('\n');

fs.writeFile('fontawesomeStyles.txt', faClassesString, function (err) {
	if (err) return console.log(err);
});

```

Maybe it could me modified as I wasn't too keen on writing the regex, so I just put up GitHub CoPilot to figure it out.

**Comment by cristian-ungureanu** [comment]
Thank you for sharing! There are more things to think about as we shouldn't break the old icons either. We'll have a look and evaluate the complexity of adding FA.
