### ISSUE TITLE
Feature to add alt-attributes

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/wp-menu-icons#196]
A feature offering the possibility to add alt-attributes to the icons could be added, as there is no option to add alt-attributes to the icons at the moment.

thread suggesting this: [https://wordpress.org/support/topic/alt-attributes-in-tag/#post-15072715](url)

**Comment by girishpanchal30** [comment]
Added alt attribute support in SVG icon, User can add/edit alt using the WordPress way.
Ref - https://tinyurl.com/y5kmvdjc

cc @cristian-ungureanu
