### ISSUE TITLE
Deprecated features with PHP 8.1

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/wp-menu-icons#197]
There are 2 warnings about using deprecated features with PHP 8.1.

How to reproduce:
1. Set the PHP version to 8.1
2. Install and activate the WP Debugging plugin
3. Check the PHP Errors section from the plugin

![tempsnip](https://user-images.githubusercontent.com/86592341/142198263-ee3456ef-da8e-49e8-872d-dc5e5ee4c9f9.png)

thread reporting this: https://wordpress.org/support/topic/php-8-1-compatability-6/#post-15076889

Menu Icons version: 0.12.9
PHP version: 8.1
WordPress version: 5.8.2

**Comment by girishpanchal30** [comment]
@MarinescuLucia I have checked the code and found the issue coming from `themeisle-sdk` I can't fix this because I'm not able to access this repo.

We can fix this issue using the below code in {path}/codeinwp/themeisle-sdk/load.php.
Line No: 31 to 38

```
if ( ( is_null( $themeisle_sdk_max_path ) || version_compare( $themeisle_sdk_version, $themeisle_sdk_max_path ) == 0 ) && apply_filters( 'themeisle_sdk_should_overwrite_path', false, $themeisle_sdk_path, $themeisle_sdk_max_path ) ) {
  $themeisle_sdk_max_path = $themeisle_sdk_path;
}

if ( is_null( $themeisle_sdk_max_version ) || version_compare( $themeisle_sdk_version, $themeisle_sdk_max_version ) > 0 ) {
  $themeisle_sdk_max_version = $themeisle_sdk_version;
  $themeisle_sdk_max_path    = $themeisle_sdk_path;
}
```

Thanks

cc @cristian-ungureanu
