### ISSUE TITLE
Font Awesome 6.0

### ISSUE THREAD

**Issue by chicknlil** [Codeinwp/wp-menu-icons#201]
The newest version of Font Awesome adds a smorgasbord of icons, including one authors have been clamoring for: Goodreads.  It also adds TikTok, which I can see just about any site using these days.

Could I please ask for consideration to have the version of Font Awesome utilized within the plugin updated to version 6.0?

Thank you!

-Ben

**Comment by twhiting9275** [comment]
LOL
Good luck with that, they haven't even bothered with adding icons from 5.1 in!

**Comment by girishpanchal30** [comment]
Hey @irinelenache,
Can you please do some tests with `Font Awesome 6.0` new icons? You add new icons here( https://tinyurl.com/22odxv8g )
Here are some free FA 6.0 icons: https://fontawesome.com/search?m=free

Related: #216
Thanks
