### ISSUE TITLE
Latest version breaks the arrow icon of the submenus on some themes

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/wp-menu-icons#208]
A few users reported that after the update to version 0.12.11, the down arrow icon that appears near a menu item that has submenu items breaks and an error square is displayed instead. This doesn't happen with Twenty Twenty, Neve or Hestia, but one user mentioned it occurs for him with Nisarg theme and I was indeed able to replicate it with that theme. 

https://wordpress.org/support/topic/updating-to-v0-12-11-breaks-legacy-menu-icon/

There are also two users that reported this issue on premium themes and one of them said that all the FontAwesome icons from his site, not just the submenu arrow icon, break with the latest version of the plugin.

https://wordpress.org/support/topic/conflicting-with-fontawesome-icons/

For all the users who reported this issue, rolling back to the previous version of the plugin solves it.

**Comment by girishpanchal30** [comment]
Hello @MarinescuLucia,

I have tested with Nisarg(Free) theme and I can't replicate this issue.
Ref: https://www.awesomescreenshot.com/image/26634226?key=ef4b46a436ee95be65fef59e7ddb83f3

Can you please get more details from the reporting users?

Thanks

**Comment by MarinescuLucia** [comment]
Hi @girishpanchal30,

[Here](https://clarifymine.s4-tastewp.com/wp-admin/) is an instance where I replicated this. I added some menu icons just for reference, but the submenu arrow icon breaks right after activating Nisarg while Menu Icons is active, even if there are no menu icons from the plugin added.

 Admin area URL: https://clarifymine.s4-tastewp.com/wp-admin 
 Username: luciamarinescu 
 Password: TB9zYXN9Ig8 

After rolling back the plugin to the previous version, the arrow is correctly displayed.

Let me know if I still should ask the users for more details.

Thank you!

**Comment by girishpanchal30** [comment]
@MarinescuLucia Thank you for checking I'll check this issue and update you here.

**Comment by girishpanchal30** [comment]
Hello @MarinescuLucia,

I have fixed the issue, Please check and do let me know if you have any issues.

Thanks

**Comment by MarinescuLucia** [comment]
@girishpanchal30 It's working fine with Nisarg now, the arrow is displayed as expected. Thank you!
