### ISSUE TITLE
Compatibility Issue With JupiterX theme plugin in v0.12.12

### ISSUE THREAD

**Issue by bznerd** [Codeinwp/wp-menu-icons#212]
Updating to version 0.12.12 caused the dropdown menu to become permanently open and cause the header to become extremely zoomed in when scrolled past.

**Comment by luca-ing** [comment]
Yep, similarly I ran into issues with my header menu, which seems to have become entirely un-styled

**Comment by purplecodes** [comment]
- this happens with menus that are created with the Elementor widget. 

@bznerd , @luca-ing - In the meantime, you can roll back to the v0.12.11 for now for the icons to display on your menu items.
