### ISSUE TITLE
Neve upsell appears even when Neve is already installed

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/wp-menu-icons#220]
I think the upsell should appear only if Neve is not installed.
After Neve is installed the Upsell Toast should disappear:
<img width="1739" alt="Screenshot 2022-07-27 at 09 56 07" src="https://user-images.githubusercontent.com/52494172/181181744-927e284e-75ef-4147-ac14-2c8c20925d00.png">

**Comment by selul** [comment]
@mghenciu, this looks more accurate tagged as a bug rather than small-improvement, what do you think?

**Comment by mghenciu** [comment]
It may be the way it was intended, so that's why I tagged it with small-improvement. Added now the bug label, also.

Essentially the idea is to have most common flows covered:
- I have **Neve installed**, and I install Menu Icons -> the upsell should be hidden
- I have **Menu Icons installed** with the Neve upsell visible, and I install Neve -> the upsell should become hidden after Neve is installed
- I install Menu Icons and Neve is **not present** -> show the upsell

**Comment by girishpanchal30** [comment]
Hey @mghenciu,
I have implemented above mentioned flow. Please check and do let me know if you have any issues.
Thanks

**Comment by mghenciu** [comment]
@girishpanchal30 , tested now and looks good!
The Neve upsell, **doesn't appear anymore if Neve is already Installed & Activated.**
