### ISSUE TITLE
Hide on mobile/desktop

### ISSUE THREAD

**Issue by Jearnobyl** [Codeinwp/wp-menu-icons#228]
There should be an option to hide the settings on mobile version. My theme for example is not showing that there is a submenu on the desktop version but is showing it on the mobile version. I need it to work on the desktop version but at the mobile version it is now showing double. That's their case in far more themes. An option that disables it on mobile/desktop version should be great.

**Comment by girishpanchal30** [comment]
Hey @Jearnobyl,

I think you can do it from your end using the below method.

if ( wp_is_mobile() ) {
     wp_nav_menu( array( 'menu' => 'mobile-menu' ) );
} else {
     wp_nav_menu( array( 'menu' => 'desktop-menu' ) );
}

You can check the `wp_is_mobile` condition before rendering the nav menu.

Thanks

**Comment by Jearnobyl** [comment]
Hi @girishpanchal30 

Where to put this code exactly? I was thinking the plugin but that gives me an error.

**Comment by girishpanchal30** [comment]
Hello @Jearnobyl,

You can put this code in your current theme header.php or any other location where you call the `wp_nav_memu`.
I hope you now understand.

Thanks
