### ISSUE TITLE
My Customizer is gone

### ISSUE THREAD

**Issue by miri4ever** [Codeinwp/wp-menu-icons#232]
If I enable this plugin, my Customizer Menu for the header image, background image just show nothing whatsoever. No gallery images, nothing.  It just displays my webpage name, but all links to customize my webpage just disappeared. I always need to turn it off if I wanted to switch my background or header image.

This only happens with 0.13.2 I made a rollback to 0.13.1 and there it's fine again.

**Comment by girishpanchal30** [comment]
Hey @miri4ever,

I've reviewed with default WordPress themes/plugins and can't replicate this issue on my local and tastewp instances. 
Can you please share more details?

Thanks
