### ISSUE TITLE
Fatal error using WP lower than 4.7

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/wp-menu-icons#257]
### Description

If i use the plugin with a WordPress version lower than 4.7, there will be a fatal error coming from the themeisle sdk https://vertis.d.pr/i/vyFH4U . On wp.org the minimum version is [4.3](https://vertis.d.pr/i/0Lc926) so i think we can raise it to 4.7

### Step-by-step reproduction instructions

1. Install a WordPress version lower than 4.7
2. Activate Menu icons plugin

### Screenshots, screen recording, code snippet or Help Scout ticket

https://vertis.d.pr/i/vyFH4U

### Environment info

PHP 7.4 / WordPress lower than 4.7 / Menu icons 0.13.7

### Is the issue you are reporting a regression

No

**Comment by vytisbulkevicius** [comment]
Updated 👌
