### ISSUE TITLE
Hide Label does not work in Menu Icons Settings

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/wp-menu-icons#265]
### Description

A user reported that even if he set it to hide the label, it is still displayed. I checked and indeed, if you select "No" for Hide Label inside the Menu Icons Settings, it has no effect. It works only when I individually set it while editing an icon.

### Step-by-step reproduction instructions

1. Go to Appearance> Menus.
2. Expand the Menu Icons Settings.
3. Switch to Current Menu.
4. Under the Hide label, select Yes.

### Screenshots, screen recording, code snippet or Help Scout ticket

https://wordpress.org/support/topic/want-to-see-icon-without-the-label/#post-17191177

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina I've reviewed this issue and fixed it with this PR https://github.com/Codeinwp/wp-menu-icons/pull/268

**Comment by irinelenache** [comment]
@girishpanchal30 The issue is fixed now, thank you 👍
