### ISSUE TITLE
Missing fa-brands?

### ISSUE THREAD

**Issue by teledyn** [Codeinwp/wp-menu-icons#267]
### Description

I have installed on the latest WP and I notice an option for 'brand' but font-awesome lists `class="fa-brands fa-mastodon"` and the mastodon logo is not found. Is there something I need to install?

### Step-by-step reproduction instructions

1. in the menu editor, click add icon and search mastodon
2. go to [https://fontawesome.com/icons/mastodon](fontawesome.com/icons/mastodon?f=brands&s=solid)

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
Hey @teledyn,

You can add a new icon through the plugin settings here: https://tinyurl.com/ykzpubl4

cc @vytisbulkevicius

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Thank you for providing a solution to this 🚀
