### ISSUE TITLE
Remove the recommendation of Advanced CSS Editor plugin

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/wp-menu-icons#278]
### What problem does this address?

On the choosing icon page, there is a recommendation for the Advanced CSS Editor plugin.

![menu-icons-advanced-css-recomm](https://github.com/Codeinwp/wp-menu-icons/assets/26867648/671863d3-e596-436f-990a-b9f7c3ddadae)

### What is your proposed solution?

I suggest removing that recommendation, as the plugin hasn't been updated for 5 years. We can keep the customizer link.

### Will this feature require documentation? (Optional)

No.

**Comment by vytisbulkevicius** [comment]
I agree, we can just remove that recommendation by removing the last part of the sentence, keeping only "You can add your own CSS using the customizer", as we don't update the mentioned plugin and have no plans of updating it so in case at some points it generates a critical error or something similar better don't recommend it.

**Comment by girishpanchal30** [comment]
@vytisbulkevicius @stefan-cotitosu I've reviewed this issue and fixed it with this PR https://github.com/Codeinwp/wp-menu-icons/pull/296
