### ISSUE TITLE
Plugin recommends Neve even when Neve is installed and activated

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/wp-menu-icons#287]
### Description

![Annotation on 2024-04-05 at 17-25-26 (1)](https://github.com/Codeinwp/wp-menu-icons/assets/3266155/73d51851-d5c8-4109-9912-8e347ceb136e)

### Step-by-step reproduction instructions

1. Have Neve installed
2. Install and activate the Menu Icons plugin

### Is the issue you are reporting a regression

No

**Comment by stefan-cotitosu** [comment]
https://wordpress.org/support/topic/neve-theme-upsell-administrators-only/#post-17527341
